# -*- encoding: utf-8 -*-

=begin
#Snap Conversions API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "snap_business/version"

Gem::Specification.new do |s|
  s.name        = "snap_business"
  s.version     = SnapBusinessSDK::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Snap Inc."]
  s.email       = ["attribution-team@snapchat.com"]
  s.homepage    = "https://snapchat.com"
  s.summary     = "The official Snap Business SDK for Ruby"
  s.description = "The official Snap Business SDK for Ruby for interacting with the Snap Conversion API and Launchpad"
  s.metadata = {
    "documentation_uri" => "https://github.com/Snapchat/business-sdk-ruby",
    "source_code_uri" => "https://github.com/Snapchat/business-sdk-ruby"
  }
  s.license = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_dependency 'concurrent-ruby', '~> 1.1'
  s.add_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_dependency 'faraday-multipart', '~> 1.0'
  s.add_dependency 'soundex', '~> 0.1'
  s.add_dependency 'digest', '~> 3.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = Dir['lib/**/*.rb']
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
